spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-route
              uri: http://auth:8090
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: micro1-route
              uri: http://micro1:3000
              predicates:
                - Path=/micro1/**
              filters:
                - StripPrefix=1

            - id: app2-route
              uri: http://app2:4000
              predicates:
                - Path=/app2/**
              filters:
                - StripPrefix=1

server:
  port: 8080
